### ISSUE TITLE
document database creation step in postgres in README.md 

### ISSUE THREAD

**Issue by micahstubbs** [moovel/teamchatviz#54]
this projects looks fantastic.  I'm stuck at this point of the dev setup described in the `README.md`:

`npm run up`

after which I see:

`[ERROR] error: role "teamchatviz" does not exist`

I'm sure that this step is obvious if you work with postgres all the time.  that said, it would be super helpful. to document the things you need to do before you can run `npm run up` successfully 😄 

![screen shot 2016-07-30 at 3 06 07 pm](https://cloud.githubusercontent.com/assets/2119400/17273377/86f83640-5667-11e6-9a42-e023f64995c5.png)

**Comment by OrKoN** [comment]
Hi @micahstubbs,

in order to create a DB in Postgres you need to start `psql`. On Linux systems you can run `sudo -u postgres psql`. On OS X you can start it via the UI of Postgres.app.

Once you are in, you can run the following commands to create a user called `teamchatviz` with the password `teamchatviz` and a database called `teamchatviz`:

```sh
CREATE DATABASE teamchatviz;
CREATE ROLE teamchatviz WITH LOGIN CREATEDB PASSWORD 'teamchatviz';
ALTER USER teamchatviz VALID UNTIL 'infinity';
ALTER DATABASE teamchatviz OWNER TO teamchatviz;
GRANT ALL ON DATABASE teamchatviz TO teamchatviz;
\c teamchatviz
ALTER SCHEMA public OWNER TO teamchatviz;
```

Please let me know if this worked for you and I will add it to the README.

**Comment by micahstubbs** [comment]
starting `psql` from the postgres mac gui

![screen shot 2016-07-31 at 1 35 01 pm](https://cloud.githubusercontent.com/assets/2119400/17279211/a57439ae-5723-11e6-92df-
2206ef848dae.png)
![screen shot 2016-07-31 at 1 35 18 pm](https://cloud.githubusercontent.com/assets/2119400/17279212/a6a4a62e-5723-11e6-825c-03db2fac6922.png)
![screen shot 2016-07-31 at 1 35 25 pm](https://cloud.githubusercontent.com/assets/2119400/17279214/a7fed062-5723-11e6-97f1-7fed37d69cb3.png)

**Comment by micahstubbs** [comment]
I think the migration succeeded

![screen shot 2016-07-31 at 1 41 00 pm](https://cloud.githubusercontent.com/assets/2119400/17279248/83cfb732-5724-11e6-9147-899d2389ffed.png)

**Comment by micahstubbs** [comment]
it works!  now have teamchatviz up and running locally 🎉
🙏  @OrKoN 
👍  for adding the text to the `README.md` 😄 

here's the emoji timeline for one of my teams:
![screen shot 2016-07-31 at 1 57 21 pm](https://cloud.githubusercontent.com/assets/2119400/17279370/f9d5d432-5726-11e6-87b7-c3ff6cf614f9.png)

**Comment by OrKoN** [comment]
thanks @micahstubbs I have added the steps to the README. I am happy that you like the project! Please let me know if you have further questions about the setup or if you have any ideas about improving the project or adding new features!
