### ISSUE TITLE
pg-promise

### ISSUE THREAD

**Issue by vitaly-t** [moovel/teamchatviz#59]
Why not use the pattern suggested in [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo)?

It provides a much cleaner approach to implementing the database layer. :wink:

**Comment by OrKoN** [comment]
@vitaly-t it seems that in the demo the db structure is tightly coupled with the application models? Also the drop/create statements accessible from the application code do not look nice :-) 

Apart from the a nice demo ;-)

P.S. using GET for all operations is not clean.

**Comment by vitaly-t** [comment]
@OrKoN 

>  it seems that in the demo the db structure is tightly coupled with the application models

It is not.

>the drop/create statements accessible from the application code do not look nice

Those are simply examples of implementing database repositories, so it is not relevant.

>using GET for all operations is not clean

From the demo code:

```js
// NOTE: We implement only GET handlers here, because:
// 1. This demo is to be tested by typing URL-s manually in the browser;
// 2. The demo's focus is on a proper database layer, not a web server.
```
