### ISSUE TITLE
Creating Heroku App Does Not Work

### ISSUE THREAD

**Issue by garethedavies** [moovel/teamchatviz#60]
Good morning,

I am currently following the instructions on getting the Heroku app and Slack app created. Everything seems to work fine but when I create the app in Heroku and click on the URL, I am just presented with a white page. I am following all of the instructions from readme.md but it just presents a white page. This has happened 3 times now.

Are you aware of any issues currently with creating the app in Heroku?

Thanks

Gareth

**Comment by OrKoN** [comment]
Hello Gareth,

sorry about that. I have not tried to start a new instance for a long time and some of our dependencies introduced breaking changes. I have locked down the dependency versions so now everything should work again 👍 Thanks for letting us know.

Best regards,
Alex

**Comment by garethedavies** [comment]
Incredible! All working!

Thanks for such a quick reply and resolution!

Gareth
